name: docs.hypofuzz.com

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Build docs
      run: |
        python -m pip install tox
        python -m tox --recreate -e docs
    - name: Upload docs
      run: |
        mv ./build/ ../docs/
        rm -r *
        mv ../docs .
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "build docs"
        git push --force origin HEAD:gh-pages
